### ISSUE TITLE
Data Release?

### ISSUE THREAD

**Issue by shayne-longpre** [kaistAI/CoT-Collection#1]
Cool work! I may have missed it, but is the data planning to be released soon?

**Comment by SeungoneKim** [comment]
Hello Shayne, thank you for your interest in our work! We were highly influenced by your Flan Collection paper:) 

We're checking the license of our data & planning to upload as soon as possible!

**Comment by thistleknot** [comment]
premature publication (pun intended)
In the meantime, there is this (flan v2, which I presume is what you are hinting at with the flan mention)
https://huggingface.co/datasets/SirNeural/flan_v2

**Comment by shayne-longpre** [comment]
@SeungoneKim Thanks for your kind words! Looking forward to using your data :)

@thistleknot That version of the Flan Collection is fine but doesn't maintain the same data mixture ratios. We recently updated our repo to have links to where you can download the [correct ones](https://github.com/google-research/FLAN/tree/main/flan/v2).
